version: '3'
services:
  api:
    build: packages/api
    image: docker.pkg.github.com/rustic-music-player/party-mode/api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`${DOMAIN}`) && Path(`/api`)"
  client:
    build: packages/client
    image: docker.pkg.github.com/rustic-music-player/party-mode/client:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`${DOMAIN}`)"
  file-storage:
    image: minio/minio
    volumes:
    - storage:/storage
    environment:
      MINIO_ACCESS_KEY: dev_root_key
      MINIO_SECRET_KEY: secret_access_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`${DOMAIN}`)"
    command: server /storage
    ports:
    - 9000:9000
networks:
  remote_gateway:
volumes:
  storage:
