[package]
name = "rustic-party-mode-extension"
version = "0.1.0"
authors = ["Max Jöhnk <maxjoehnk@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/rustic-music-player/rustic"
homepage = "https://github.com/rustic-music-player/rustic"

[lib]
crate-type = ["cdylib"]

[dependencies]
failure = "0.1"
rustic-core = { git = "https://github.com/rustic-music-player/rustic.git" }
rustic-extension-api = { git = "https://github.com/rustic-music-player/rustic.git" }
async-trait = "0.1"
tokio-tungstenite = "0.14"
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread", "macros"] }
futures = "0.3"
rand = { version = "0.8", features = ["small_rng"] }
futures-util = "0.3.5"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
